apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "matchflix.fullname" . }}-db-es
  labels:
    {{- include "matchflix.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.esoTokenName }}

  target:
    name: {{ .Values.dbES.secretName }}
    creationPolicy: Owner

  dataFrom:
  - extract: 
      key: {{ .Values.dbES.sourceSecretName }}
      conversionStrategy: Default
      decodingStrategy: None

---


apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "matchflix.fullname" . }}-coturn-es
  labels:
    {{- include "matchflix.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.esoTokenName }}

  target:
    name: {{ .Values.coturnES.secretName }}
    creationPolicy: Owner

  dataFrom:
  - extract: 
      key: {{ .Values.coturnES.sourceSecretName }}
      conversionStrategy: Default
      decodingStrategy: Auto
