apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
spec:
  capacity:
    storage: {{ .Values.db.storageSize | default "10Gi" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql-{{ .Release.Name }}"  # Path on the local host
