apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-eso-token
            key: token
            namespace: external-secrets
      projectID: "65100175"